version: "3.9"

services:
  backend:
    build: 127.0.0.1:5000/switch-backend
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 128M